[package]
name = "ensemble"
version = "0.0.1"
readme = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A Laravel-inspired ORM"

[dependencies]
rbs = "4.3.3"
sha256 = "1.4.0"
tokio = "1.32.0"
serde = "1.0.183"
itertools = "0.11.0"
Inflector = "0.11.4"
thiserror = "1.0.44"
async-trait = "0.1.73"
validator = { version = "0.16.1", optional = true }
serde_json = { version = "1.0.105", optional = true }
ensemble_derive = { version = "0", path = "../ensemble_derive" }
rbdc-pg = { version = "4.3.12", default-features = false, optional = true }
rbdc-mysql = { version = "4.3.12", default-features = false, optional = true }
rbdc-sqlite = { version = "4.3.12", default-features = false, optional = true }
rbatis = { version = "4.3.12", default-features = false, features = [
    "default_mode",
] }

[dev-dependencies]
axum = "0.6.20"
uuid = { version = "1.4.1", features = ["serde"] }


[features]
default = ["native-tls", "mysql", "json"]

mysql = ["dep:rbdc-mysql"]
postgres = ["dep:rbdc-pg"]
sqlite = ["dep:rbdc-sqlite"]
json = ["dep:serde_json", "ensemble_derive/json"]
rustls = [
    "rbatis/tls-rustls",
    "rbdc-pg?/tls-rustls",
    "rbdc-mysql?/tls-rustls",
    "rbdc-sqlite?/tls-rustls",
]
native-tls = [
    "rbatis/tls-native-tls",
    "rbdc-pg?/tls-native-tls",
    "rbdc-mysql?/tls-native-tls",
    "rbdc-sqlite?/tls-native-tls",
]
