[package]
name = "ensemble"
version = "0.0.0"
readme = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A Laravel-inspired ORM"

[dependencies]
rbs = "4.3.3"
serde = "1.0.183"
thiserror = "1.0.44"
async-trait = "0.1.73"
serde_json = "1.0.105"
rbdc-mysql = { version = "4.3.12", default-features = false }
ensemble_derive = { version = "0", path = "../ensemble_derive" }
rbatis = { version = "4.3.12", default-features = false, features = [
    "default_mode",
] }

[features]
default = ["native-tls"]
rustls = ["rbatis/tls-rustls", "rbdc-mysql/tls-rustls"]
native-tls = ["rbatis/tls-native-tls", "rbdc-mysql/tls-native-tls"]

[dev-dependencies]
chrono = { version = "0.4.26", features = ["serde"] }
tokio = { version = "1.32.0", features = ["rt", "macros", "rt-multi-thread"] }
